version: '2.1'
services:
  enviro:
    build: ./enviro
    network_mode: host
    privileged: true
    restart: always
    labels:
      io.resin.features.dbus: '1'
      io.resin.features.firmware: '1'
      io.resin.features.kernel-modules: '1'
      io.resin.features.resin-api: '1'
      io.resin.features.supervisor-api: '1'
