on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Balena Push
      uses: amingilani/push-to-balenacloud@v1.0.1
      with:
        api-token: ${{ secrets.BALENA_API_TOKEN }}
        application-name: home-dash
