name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bulv1ne/python-style-check@master

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Balena Push
      uses: theaccordance/balena-push@v1.0.0
      with:
        api-token: ${{ secrets.BALENA_API_TOKEN }}
        application-name: home-dash
